### ISSUE TITLE
Run in foreground/prevent daemon?

### ISSUE THREAD

**Issue by scurvy** [unixsurfer/anycast_healthchecker#11]
Is there an option to run the healthchecker in the foreground? This would be beneficial for those of us who run things like daemontools.

**Comment by unixsurfer** [comment]
No, it isn't possible at the moment.
But, I mentioned in the release notes of 0.7.4 version that in the upcoming 0.8.0 version will drop support for daemon. So, you can simply run the tool in the foreground. Moreover, we are going to simplify the logging by emitting logs to stdout and let systemd to forward them to a syslog daemon. Stderr messages will be also forwarded to syslog.

Last but not least, we are going to emit structured logging (simple JSON) to syslog over UDP. This has the benefit of not blocking anycast-healthchecker when emits log messages and also avoiding the crash on service check threads when disk is full. BTW: emitting logs to stdout is a blocking operation.

This new setup will be very configurable, so users can enable either one or both logging destinations.

**Comment by unixsurfer** [comment]
In the no-daemon branch, you find the code that runs anycast-healthchecker in foreground by default.
We don't daemonize ourself anymore
