### ISSUE TITLE
Question: can this be configured for use with RIP ?

### ISSUE THREAD

**Issue by zerthimon** [unixsurfer/anycast_healthchecker#19]
Can anycast_healthchecker be configured for use with RIP ?
What's would the config look like ?

**Comment by unixsurfer** [comment]
I haven't used RIP for many many years, but I guess the filtering we do in Bird is protocol agnostic. So, it should work.

**Comment by zerthimon** [comment]
I'll try to confgure it for RIP and will post config if it works. Thanks.

**Comment by zerthimon** [comment]
Indeed, it works!
```
protocol rip RIP1 {
   description "link to the core";
   interface "em1" {
       mode broadcast;
   };
   import none;
   export where match_route();
}
```
other configs are as in the documentation.

@unixsurfer  thanks for great software!
closing ...
