### ISSUE TITLE
Update debian/changelog

### ISSUE THREAD

**Issue by XioNoX** [unixsurfer/anycast_healthchecker#20]
debian/changelog is still on 0.8.1 could it be updated to 0.9.0?

Thanks!

**Comment by unixsurfer** [comment]
No objections from me.@BarbarossaTM, can I simply bump the number@

**Comment by BarbarossaTM** [comment]
Hi,

I guess it would be nice to keep some changelog, like this:

```
diff --git a/debian/changelog b/debian/changelog
index 713d943..c3ae756 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,3 +1,9 @@
+anycast-healthchecker (0.9.0-1) stable; urgency=medium
+
+  * Release version 0.9.0
+
+ -- Pavlos Parissis <you@some.domain>  Tue, 04 Jun 2019 22:20:19 +0200
+
 anycast-healthchecker (0.8.1-1) stable; urgency=medium

```

As the changelog should be copied into the Debian package, copying the items wouldn't make much sense to me and as far as I've seen there have been no changes to the packaging.

Hope that helps :-)

Best
Max

**Comment by unixsurfer** [comment]
Thanks for the reply. I am traveling right now and when I back home I will make the change.
