### ISSUE TITLE
check_anycast_healthchecker.py improvements

### ISSUE THREAD

**Issue by XioNoX** [unixsurfer/anycast_healthchecker#21]
While reviewing an internal change (https://gerrit.wikimedia.org/r/c/operations/puppet/+/520643/1/modules/profile/files/bird/check_anycast_healthchecker.py)
One of our engineers made a couple feedbacks that could be implemented upstream.

First for https://github.com/unixsurfer/anycast_healthchecker/blob/master/contrib/nagios/check_anycast_healthchecker.py#L66
`def running(pid):`
> I'd name this is_running, but (see below) maybe you actually want pid_is_healthchecker

Second for https://github.com/unixsurfer/anycast_healthchecker/blob/master/contrib/nagios/check_anycast_healthchecker.py#L83
`os.kill(pid, 0)`
> You can (IMO) do a better job checking what you mean to check, and eliminate the need for root privileges, if you instead check that /proc/$PID/exe symlinks to the binary name you expect.
  return "anycast-healthchecker" in os.readlink("/proc/{}/exe".format(pid))
ought to do it?

Please let us know what you think.

**Comment by unixsurfer** [comment]
Good morning or afternoon @XioNoX,

I agree with both comments! I am about to leave on vacation and I will try to adjust the code during the commute.

I would like to bring to your attention that since a3ba7cd012e6a575d57c869a2fc9896c097ef5fa we don't need that check as the absence of a thread will trigger a restart, which is the only action you take in 99.99% of cases you receive a critical alert; auto-healing is on :-)


Thanks a lot for your feedback,
Pavlos

**Comment by unixsurfer** [comment]
Looking at the link of `/proc/[pid]/exe` isn't going to work as it points to python executable for my development environment.
```
ls -ls /proc/6711/exe
0 lrwxrwxrwx 1 id id 0 Jul 20 19:32 /proc/6711/exe -> /home/pparissis/.virtualenvs/python37/bin/python3
```

Currently, I don't have access to a production server to check where `/proc/[pid]/exe` points to, but even it points to `anycast-healthchecker` this is approach is suboptimal as it doesn't work in a dev env.

**Comment by unixsurfer** [comment]
If `check_anycast_healthchecker.py` runs under the same user as `anycast-healthchecker` then you don't need **root** privileges. Going to adjust the docstring `running()` as it is misleading.

**Comment by XioNoX** [comment]
Thanks for the quick reply!
Good to know about a3ba7cd.

**Comment by unixsurfer** [comment]
I am considering to close this issue as I don't think I need to fix anything.
@XioNoX what do you think about it ?

**Comment by XioNoX** [comment]
For sure, yeah! Thanks again!
