### ISSUE TITLE
failed to acquire a lock by creating an abstract namespace socket on FreeBSD 12.1

### ISSUE THREAD

**Issue by EwaldvanGeffen** [unixsurfer/anycast_healthchecker#23]
1. clean FreeBSD installation,
2. added py37-pip and used it to install anycast_healthchecker
3. running /usr/local/bin/anycast-healthchecker results in

`failed to acquire a lock by creating an abstract namespace socket: [Errno 2] No such file or directory`

I'm not sure this is because the sysvinit support was removed or something else is lacking on my BSD. It could be misconfiguration? From what I read abstract domain sockets are security wormholes?

Also service ip_check_disabled must be true because the lack of iproute2 on FreeBSD https://github.com/unixsurfer/anycast_healthchecker/blob/f69e584b6e94ba3202c6590e2420467409bc36a7/anycast_healthchecker/servicecheck.py#L133

I think we could write something around this (ifconfig fallback) or maybe there's a python library that abstracts the OS tooling away?

Otherwise everything seems to work as required (bird2+unbound+this = [config](http://blog.abcdef.be/2020/05/unbound-dns-resolver-using-anycast-bgp-with-bird2-anycast-healthchecker-and-supervisord-on-freebsd-12-1/))

today was good day

**Comment by EwaldvanGeffen** [comment]
ip_check_disabled is a must for lack of iproute2 package on FreeBSD https://github.com/unixsurfer/anycast_healthchecker/blob/f69e584b6e94ba3202c6590e2420467409bc36a7/anycast_healthchecker/servicecheck.py#L133

**Comment by unixsurfer** [comment]
Abstract namespaces are available only in Linux.
