### ISSUE TITLE
Feature request: ACAST_PS_ADVERTISE should be purged if no service checks are defined.

### ISSUE THREAD

**Issue by jocado** [unixsurfer/anycast_healthchecker#3]
Hi,

I've been playing with the anycast_healthchecker, and it's working well for us :)

One slight issue, is that if the daemon is started with no vips/checks defined, the daemon just exists.  It would be good [ for us at least ]  if it cleared any undeclared vips from ACAST_PS_ADVERTISE before it exited.  Otherwise, removing all vips from a host [  as can be required in a dynamic environment ] becomes a manual process.

It could be a config option it it doesn't suit every need of course.

I could look at implementing this myself.  But thought I'd raise a ticket in the first instance and see where it went.

Thanks!

**Comment by unixsurfer** [comment]
Hi, 

Your request makes sense and I will definitely add this functionality. 
ACAST_PS_ADVERTISE can't be empty as bird will refuse to start, so the dummy ip prefix will be the only element in that list. 

I am wondering if I should make this new behaviour configurable in order to avoid surprises.

**Comment by jocado** [comment]
Great :)

When I say clear undeclared VIPs, I mean just as you say, remove all but the dummy ip prefix.  And yes, I agree it should be a configurable option for sure.

If there's anything I can do to help, like be an alpha/beta tester, please let me know!

Thanks.

**Comment by unixsurfer** [comment]
Work is not completed as we exit on startup when no configuration is present before we perform the sanity check on IP-Predfixes

**Comment by unixsurfer** [comment]
@jocado, I finally managed to find time to work on your requests. I have implemented the purge of IP-Prefixes without a service check associated with them. *purge_ip_prefixes* setting in the daemon section must be set to `true` in order for the purge to take place. I also changed the behaviour of the daemon when there aren't any service checks configured, it doesn't exist anymore in this case.

Please test it yourself and let me know.

**Comment by unixsurfer** [comment]
@jocado, just released 0.6.2 version which has the fix you want. It is available on PyPI, so use pip install -U anycast-healthchecker to get it

**Comment by jocado** [comment]
@unixsurfer I've only had a short time to test, but initially in the lab this seems to work well - thanks very much for your support with this :)

**Comment by unixsurfer** [comment]
@jocado,  nice to know it works for you. Let me know if you run into any issues. I  have tested thoroughly,  but you never know.
