### ISSUE TITLE
Daemon can hang indefinitely if disk fills up

### ISSUE THREAD

**Issue by jocado** [unixsurfer/anycast_healthchecker#8]
Hi,

I've seen this in production, and reproduced it in the lab.  It doesn't seem to happen every time, but it didn't take long to reproduce.

If the disk fills up, the process can hang and wait for ever, even after the disk space is restored.

strace show the process just hangs on a FUTEX.
```
# strace -p 18014 -f
Process 18014 attached
futex(0x158fe10, FUTEX_WAIT_PRIVATE, 0, NULL
```

I think it would be better if the process crashed, as the init system is then aware that the daemon is dead, and can even take care of trying to start it again.

I'm not sure of the best way to achieve this, but googling around seems to suggest that setting the threads as daemon threads will cause the entire program to exit if no alive daemon threads are left.

So something like:

```
                _thread = ServiceCheck(
                    service,
                    _config,
                    self.action,
                    self.log)
                _thread.setDaemon(True)
                _thread.start()
```

..but I'm not sure how valid that is :)

Anyhow, as ever, thanks for the help, and let me know if you need any help testing.

Thanks!

Cheers,
Just

**Comment by unixsurfer** [comment]
Hi Just,

When you say that the disk was full, I assume you meant the file system that holds the log files was full. Is my assumption correct ?

Did you check if the service checks were still working while there wasn't any space available?
Threads that run the checks, should have been crashed with an exception about no more space on device on the first use of logging functionality.

It is very normal behavior to see the parent process doing nothing if all threads has crashed, as it doesn't receive any tasks to perform. I think you witnessed exactly that behavior.

There is a nagios check script, which alerts when running threads are less the expected. You can use for alerting if you want.

**Comment by jocado** [comment]
Hi.


Sorry for not specifying, but yes it is the logging volume that filled up.
I can confirm that the service checks stopped working as well.

I guess the problem as I see it is not that the checks stop, but that they don't start again without manual intervention after disk space is restored.
Whereas, if the whole daemon died, the init system could try and start it again automatically (upstart in this case).


If you provide a link, I will have a look at the nagios script, but I would use it as a basis for auto-healing rather than alerting in my case :)


If the behaviour I would prefer is something you aren't very keen on, I could always have a look at implementing it as a configurable option or some such.  I'll have a think about that.

Thanks for your help :)

**Comment by unixsurfer** [comment]
Hi,

You can find the nagios script under contrib/nagios directory, I am sorry not mentioning earlier.
If you have monit available then it is trivial to use it to restart the daemon if the script reports errors.

Cheers,
Pavlos

**Comment by jocado** [comment]
Hi - no problem.

I've decided to just run something like this in cron:

```
#!/bin/bash
if [ -f /run/anycast-healthchecker/anycast-healthchecker.pid ] ; then
	if [ $(ps huH p `pgrep --pidfile /run/anycast-healthchecker/anycast-healthchecker.pid 2>/dev/null` | wc -l) -lt 2 ] ; then
		kill `pgrep --pidfile /run/anycast-healthchecker/anycast-healthchecker.pid` >/dev/null 2>&1
	fi
fi
```

It works fine - I'll close this :)
